### ISSUE TITLE
Implement Overlay icons.

### ISSUE THREAD

**Issue by andirsun** [casasfernando/wingpanel-indicator-airpods#1]
Hey!, I really like your project and as a elementary os developer I am developing new section of power settings. 
I think you can use overlay to show the battery over each airpod and case. 
![Screenshot from 2021-08-17 10-35-47](https://user-images.githubusercontent.com/22928302/129756629-ec8d13f5-d993-4e90-847f-8f50a1abe76b.png)

Code example
```
var badge_icon = new Gtk.Image.from_icon_name ("battery-icon", Gtk.IconSize.BUTTON) {
    halign = Gtk.Align.END,
    valign = Gtk.Align.END
};
var overlay = new Gtk.Overlay ();
overlay.add (airpod-icon);
overlay.add_overlay (badge_icon);
```

**Comment by casasfernando** [comment]
Thanks for reaching out @andirsun I really like your suggestion.
I will give it a try and see how it looks.

**Comment by casasfernando** [comment]
@andirsun I'm working on this, and it looks better. :)

Only doubt I have is regarding the icon sizes.
I tried with 16px and 24px for the battery status, but one looks a bit small and the other a bit large. Which size are you guys using in the power indicator of elementary?

**Comment by casasfernando** [comment]
@andirsun, what about the device icon size. I'm using 48px, but maybe is too much. I tried to look at the code for the power indicator device row (https://github.com/elementary/wingpanel-indicator-power/blob/master/src/Widgets/DeviceRow.vala), but unless I got it wrong (which is perfectly possible) the power indicator is using 48px for the device icon and 32px for the battery status icon?

**Comment by andirsun** [comment]
@casasfernando you can use 32 for device and 24 for battery.

**Comment by casasfernando** [comment]
Changed implemented in commit https://github.com/casasfernando/wingpanel-indicator-airpods/commit/e561310157d6da7827f99493bf1d1194b628898c

Please download the latest release from: https://github.com/casasfernando/wingpanel-indicator-airpods/releases

Thanks.
